Repository 2020sp93078/Calorie-Tracker, pull requests merged in 2021-12, with the labels that each got.

#13 [FIX] Added form validation
  lib/screens/user_info_screen/user_info_screen.dart
Labels: bug-fix

#15 [FIX] Moved Colors to constant file
  lib/common/constants.dart
  lib/screens/calorie_info_screen/calorie_info_screen.dart
  lib/screens/calorie_info_screen/widgets/calorie_info.dart
  lib/screens/health_status_screen/health_status_screen.dart
  lib/screens/home_screen/widgets/action_button.dart
  lib/screens/home_screen/widgets/camera_button.dart
  lib/screens/home_screen/widgets/daily_progress.dart
  lib/screens/login_screen/login_screen.dart
  lib/screens/sport_event_screen/sport_event_screen.dart
  pubspec.lock
Labels: enhancement

#24 [FIX] Displaying negative value in calorie
  lib/screens/home_screen/home_screen.dart
Labels: bug-fix

#28 [ENHANCEMENT] Refactored sports event page
  lib/screens/sport_event_screen/sport_event_screen.dart
  lib/services/sport_event_service.dart
Labels: enhancement

#30 [DOCUMENTATION] Added Logo and Project description
  README.md
Labels: documentation

#31 [DOCUMENTATION]Added Features section.
  README.md
Labels: documentation

#34 [DOCUMENTATION] added installation and build steps
  README.md
Labels: documentation

#35 [FIX]Responsive home page
  lib/screens/home_screen/home_screen.dart
  lib/screens/home_screen/widgets/action_button.dart
  lib/screens/home_screen/widgets/daily_progress.dart
Labels: bug-fix

#36 [FIX]Moved API keys to env file
  .gitignore
  lib/services/food_calorie_info_service.dart
  pubspec.lock
  pubspec.yaml
Labels: bug-fix
